# Private Ansible playbook
#
# Copyright (C) 2018 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

##############################################################################
# Install and configure packages required for KDE desktop environment
##############################################################################

- name: Install KDE package
  package:
    name: plasma-desktop
    state: present

- name: Install SDDM configuration plugin package
  package:
    name: sddm-kcm
    state: present

- name: Install Konsole package
  package:
    name: konsole
    state: present

- name: Install Dolphin package
  package:
    name: dolphin
    state: present

- name: Install Ark Archive manager package
  package:
    name: ark
    state: present

- name: Install Gwenview image viewer package
  package:
    name: gwenview
    state: present

- name: Install Okular document viewer package
  package:
    name: okular
    state: present

- name: Check if networkmanager package is installed
  shell: pacman -Q networkmanager
  ignore_errors: yes
  register: check_networkmanager

- name: Install the NetworkManager applet
  package:
    name: plasma-nm
    state: present
  when: check_networkmanager.rc == 0

- name: Install powerdevil package
  package:
    name: powerdevil
    state: present
  when: kde_install_powerdevil

- name: Install PulseAudio package
  package:
    name: pulseaudio
    state: present

- name: Install PulseAudio applet
  package:
    name: plasma-pa
    state: present

##############################################################################
# Theme and design configuration
##############################################################################

- name: Install breeze-gtk package
  package:
    name: breeze-gtk
    state: present

- name: Install GTK configuration plugin
  package:
    name: kde-gtk-config
    state: present

