# Private Ansible playbook
#
# Copyright (C) 2018 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- hosts: arch_linux_desktop
  vars:
    - firefox_users: ['{{username}}']
    - ssh_agent_users: ['{{username}}']
    - syncthing_users: ['{{username}}']
    - vbox_allowed_users: ['{{username}}']
    - vbox_sf_users: ['{{username}}']
    - sane_frontends: [skanlite, gscan2pdf]
    - android_dev_user: '{{username}}'
  roles:
    - common
    - arch_reflector
    - aurutils
    - security_keys
    - systemd_ssh_agent
    - networkmanager
    - role: local_unbound
      when: install_unbound is defined and install_unbound
    - role: fwupd
      when: install_fwupd is defined and install_fwupd
    - role: tlp
      when: install_tlp is defined and install_tlp
    - role: ansible_controller
      when: install_ansible is defined and install_ansible
    - kde
    - role: syncthing
      when: install_syncthing is defined and install_syncthing
    - role: virtualbox
      when: install_vbox is defined and install_vbox
    - role: qemu
      when: install_qemu is defined and install_qemu
    - role: desktop_applications
      when: install_applications is defined and install_applications
    - role: android_dev
      when: install_android_dev is defined and install_android_dev
