namespace: tfkhim
name: linux_setup
version: 0.0.1
readme: README.md
authors:
- Thomas Himmelstoss <9889638+tfkhim@users.noreply.github.com>
license:
- MIT
repository: https://github.com/tfkhim/ansible-linux-setup
