# Private Ansible playbook
#
# Copyright (C) 2018 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

##############################################################################
# Install and configure Firefox
##############################################################################

- name: Install Firefox package
  package:
    name: firefox
    state: present

- name: Install Firefox language packs
  package:
    name: '{{item}}'
    state: present
  with_items:
    - firefox-i18n-de

##############################################################################
# Install KeePass
##############################################################################

- name: Install KeePass package
  package:
    name: keepass
    state: present

- name: Install xdotool package for autotyping
  package:
    name: xdotool
    state: present

##############################################################################
# Install a text editor
##############################################################################

- name: Install Visual Studio Code
  package:
    name: code
    state: present

