# Private Ansible playbook
#
# Copyright (C) 2018 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

##############################################################################
# Install and configure Firefox
##############################################################################

- name: Install Firefox package
  package:
    name: firefox
    state: present

- name: Install Firefox language packs
  package:
    name: '{{item}}'
    state: present
  with_items:
    - firefox-i18n-de

- name: Create .mozilla folder
  become_user: '{{item}}'
  become: yes
  file:
    path: /home/{{item}}/.mozilla
    state: directory
    mode: u=rwx,g=,o=
  loop: '{{firefox_users}}'

- name: Create firefox folder
  become_user: '{{item}}'
  become: yes
  file:
    path: /home/{{item}}/.mozilla/firefox
    state: directory
    mode: u=rwx,g=,o=
  loop: '{{firefox_users}}'

- name: Create profile folder
  become_user: '{{item}}'
  become: yes
  file:
    path: /home/{{item}}/.mozilla/firefox/abcdefgh.default
    state: directory
    mode: u=rwx,g=,o=
  loop: '{{firefox_users}}'

- name: Copy profile configuration file
  become_user: '{{item}}'
  become: yes
  copy:
    force: no
    src: profiles.ini
    dest: /home/{{item}}/.mozilla/firefox
    mode: u=rw,g=r,o=r
  loop: '{{firefox_users}}'

- name: Create the times.json file
  become_user: '{{item}}'
  become: yes
  template:
    force: no
    src: times.json.j2
    dest: /home/{{item}}/.mozilla/firefox/abcdefgh.default/times.json
    mode: u=rw,g=,o=
  loop: '{{firefox_users}}'

- name: Create an empty perfs.js file
  become_user: '{{item}}'
  become: yes
  copy:
    force: no
    content: ''
    dest: /home/{{item}}/.mozilla/firefox/abcdefgh.default/prefs.js
    mode: u=rw,g=,o=
  loop: '{{firefox_users}}'

- name: Copy the user.js file
  become_user: '{{item}}'
  become: yes
  copy:
    src: user.js
    dest: /home/{{item}}/.mozilla/firefox/abcdefgh.default
    mode: u=rw,g=,o=
  loop: '{{firefox_users}}'

##############################################################################
# Install Thunderbird
##############################################################################

- name: Install Thunderbird package
  package:
    name: [thunderbird, thunderbird-i18n-de]
    state: present

##############################################################################
# Install VLC media player
##############################################################################

- name: Install VLC package
  package:
    name: vlc
    state: present

##############################################################################
# Install Java runtime
##############################################################################

- name: Install Java runtime environment
  package:
    name: jre-openjdk
    state: present

##############################################################################
# Install KeePassXC
##############################################################################

- name: Install KeePassXC package
  package:
    name: keepassxc
    state: present

##############################################################################
# Install a text editor
##############################################################################

- name: Build and publish visual-studio-code-bin AUR package
  become_user: '{{aur_build_user}}'
  become: yes
  command: aur sync --noview visual-studio-code-bin

- name: Install visual-studio-code-bin
  pacman:
    name: visual-studio-code-bin
    state: present
    update_cache: yes

##############################################################################
# Install a LaTex
##############################################################################

- name: Install TeX Live distribution
  package:
    name:
      - texlive-core
      - texlive-binextra
      - texlive-lang
      - texlive-fontsrecommended
      - texlive-fontsextra
      - texlive-langgerman
    state: present

##############################################################################
# Install a LibreOffice
##############################################################################

- name: Install LibreOffice distribution
  package:
    name: libreoffice-fresh
    state: present

##############################################################################
# Install Flatpak
##############################################################################

- name: Install Flatpak
  package:
    name: flatpak
    state: present

##############################################################################
# Install CUPS
##############################################################################

- name: Install CUPS package
  package:
    name: [cups, foomatic-db-engine, foomatic-db-gutenprint-ppds, gutenprint]
    state: present

- name: Enable the CUPS service
  service:
    name: cups
    enabled: yes
    state: started

##############################################################################
# Install SANE
##############################################################################

- name: Install SANE package
  package:
    name: sane
    state: present

- name: Install SANE frontend package
  package:
    name: '{{sane_frontends}}'
    state: present
  when: sane_frontends is defined
