# Private Ansible playbook
#
# Copyright (C) 2018 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

##############################################################################
# Install and configure xorg server package
##############################################################################

- name: Install Xorg server package
  package:
    name: xorg-server
    state: present

##############################################################################
# Install fonts
##############################################################################

- name: Install DejaVu font
  package:
    name: ttf-dejavu
    state: present

- name: Install Liberation font
  package:
    name: ttf-liberation
    state: present

- name: Install Noto Emoji font
  package:
    name: noto-fonts-emoji
    state: present

##############################################################################
# Usability configuration
##############################################################################

- name: Install keyboard layout
  copy:
    src: 90_xkb_layout.conf
    dest: /etc/X11/xorg.conf.d/90_xkb_layout.conf
    owner: root
    group: root

