# Private Ansible playbook
#
# Copyright (C) 2018 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Create the directory for the key files
  file:
    path: /root/secure-boot
    state: directory
    mode: u=rwx,g=,o=

- name: Copy DB.key and DB.crt files
  copy:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    mode: u=rw,g=,o=
  with_items:
    - {src: '{{secure_boot_dir}}/db.key', dest: '/etc/efi-keys/DB.key'}
    - {src: '{{secure_boot_dir}}/db.crt', dest: '/etc/efi-keys/DB.crt'}

- name: Build AUR package
  become_user: '{{aur_build_user}}'
  become: yes
  command: aur sync sbupdate-git

- name: Install AUR package with pacman
  pacman:
    name: sbupdate-git
    state: present
    update_cache: yes

- name: Create a backup of sbupdate configuration
  copy:
    remote_src: yes
    force: no
    src: /etc/sbupdate.conf
    dest: /etc/sbupdate.conf.orig

- name: Update sbupdate configuration
  lineinfile:
    path: /etc/sbupdate.conf
    regex: '^#?{{item.key}}=.*$'
    line: '{{item.key}}="{{item.value}}"'
  with_items:
    - {key: CMDLINE_DEFAULT, value: '{{secure_boot_kernel_command_line}}'}
    - {key: ESP_DIR, value: '{{secure_boot_esp_dir}}'}
    - {key: OUT_DIR, value: '{{secure_boot_out_dir}}'}
