# Private Ansible playbook
#
# Copyright (C) 2018 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

##############################################################################
# Install and configure reflector
##############################################################################

# See: https://wiki.archlinux.org/index.php/Reflector

- name: Install reflector package
  package:
    name: reflector
    state: present

- name: Copy systemd service unit file
  copy:
    src: reflector.service
    dest: /etc/systemd/system

- name: Copy systemd timer unit file
  copy:
    src: reflector.timer
    dest: /etc/systemd/system

- name: Enable systemd timer
  service:
    name: reflector.timer
    enabled: yes
    state: started
