# Private Ansible playbook
#
# Copyright (C) 2020 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

##############################################################################
# Install and configure VirtualBox guest
##############################################################################

- name: Install the VirtualBox guest additions
  package:
    name: [virtualbox-guest-utils]
    state: present

- name: Start VirtualBox guest services (clock sync, automounting, ...)
  service:
    name: vboxservice
    enabled: yes
    state: started

- name: Add users to 'vboxsf' group
  user:
    name: '{{item}}'
    groups: vboxsf
    append: yes
  with_items: '{{vbox_sf_users}}'
