# Private Ansible playbook
#
# Copyright (C) 2018 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Create a directory for the script and configuration
  file:
    path: '{{uefi_kernel_update_install_dir}}'
    state: directory
    owner: root
    group: root

- name: Copy script file
  template:
    src: update.sh.j2
    dest: '{{uefi_kernel_update_install_dir}}/update.sh'
    owner: root
    group: root
    mode: u+x

- name: Copy configuration template
  template:
    src: update.config.j2
    dest: '{{uefi_kernel_update_install_dir}}/update.config'
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Create a directory for the pacman hook file
  file:
    path: /etc/pacman.d/hooks
    state: directory
    owner: root
    group: root

- name: Copy pacman hook template
  template:
    src: pacman.hook.j2
    dest: /etc/pacman.d/hooks/999-uefi-kernel-update.hook
    owner: root
    group: root

