# Private Ansible playbook
#
# Copyright (C) 2019 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Restart sshd service
  service:
    name: ssh
    enabled: '{{ssh_enable_daemon}}'
