# Private Ansible playbook
#
# Copyright (C) 2022 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Install required packages
  package:
    name:
      - chezmoi
      - sway
      - swaybg
      - swayidle
      - swaylock
      - alacritty
      - waybar
      - ttf-nerd-fonts-symbols-1000-em
      - wofi
      - brightnessctl
      - pipewire
      - pipewire-pulse
      - wireplumber
      - pavucontrol
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - dunst
    state: present

- name: Create directories for sway-workspace-extras
  file:
    path: '{{item}}'
    state: directory
    mode: u=rwx,g=rx,o=rx
  loop:
    - '/opt'
    - '/opt/sway-workspace-extras'

- name: Download sway-workspace-extras binary
  get_url:
    url: 'https://github.com/tfkhim/sway-workspace-extras/releases/download/{{sway_workspace_extras_version}}/binary-v{{sway_workspace_extras_version}}-linux-x86_64'
    dest: '/opt/sway-workspace-extras/sway-workspace-extras'
    mode: 'u=rwx,g=rx,o=rx'
    checksum: '{{sway_workspace_extras_checksum}}'

- name: Create config directories
  become_user: '{{sway_user}}'
  become: yes
  file:
    path: '/home/{{sway_user}}/{{item}}'
    state: directory
    mode: u=rwx,g=rx,o=rx
  loop:
    - '.local'
    - '.local/share'
    - '.local/share/applications'

- name: Copy *.desktop entries
  become_user: '{{sway_user}}'
  become: yes
  copy:
    src: '{{item}}'
    dest: '/home/{{sway_user}}/.local/share/applications'
  loop:
    - 'hibernate.desktop'
    - 'logout.desktop'
    - 'reboot.desktop'
    - 'shutdown.desktop'
