# Private Ansible playbook
#
# Copyright (C) 2022 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Install required packages
  package:
    name:
      - chezmoi
      - sway
      - swaybg
      - swayidle
      - swaylock
      - alacritty
      - waybar
      - ttf-liberation
      - cantarell-fonts
      - ttf-nerd-fonts-symbols
      - wofi
      - brightnessctl
      - kanshi
      - wl-clipboard
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pavucontrol
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - dunst
      - qt5-wayland
      - xorg-xwayland
      - grim
      - slurp
      - swappy
      - nemo
      - kitty
      - ranger
      # The python-pillow library is a requirement for ranger to
      # use Kitty for image previews
      - python-pillow
    state: present

- name: Create directories for sway-workspace-extras
  file:
    path: '{{item}}'
    state: directory
    mode: u=rwx,g=rx,o=rx
  loop:
    - '/opt'
    - '/opt/sway-workspace-extras'

- name: Download sway-workspace-extras binary
  get_url:
    url: 'https://github.com/tfkhim/sway-workspace-extras/releases/download/{{sway_workspace_extras_version}}/binary-v{{sway_workspace_extras_version}}-linux-x86_64'
    dest: '/opt/sway-workspace-extras/sway-workspace-extras'
    mode: 'u=rwx,g=rx,o=rx'
    checksum: '{{sway_workspace_extras_checksum}}'

- name: Build wl-mirror AUR package
  become_user: '{{aur_build_user}}'
  become: yes
  command: aur sync --noview wl-mirror

- name: Install wl-mirror package with pacman
  pacman:
    name: wl-mirror
    state: present
    update_cache: yes
