# Private Ansible playbook
#
# Copyright (C) 2022 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Install required packages
  package:
    name:
      - sway
      - swaybg
      - swayidle
      - swaylock
      - alacritty
      - waybar
      - ttf-nerd-fonts-symbols-1000-em
      - wofi
      - brightnessctl
    state: present

- name: Create config directories
  become_user: '{{sway_user}}'
  become: yes
  file:
    path: '/home/{{sway_user}}/{{item}}'
    state: directory
    mode: u=rwx,g=rx,o=rx
  loop:
    - '.config'
    - '.config/sway'
    - '.config/waybar'
    - '.config/alacritty'
    - '.local'
    - '.local/share'
    - '.local/share/applications'

- name: Copy main Sway configuration file
  become_user: '{{sway_user}}'
  become: yes
  copy:
    src: 'sway.config'
    dest: '/home/{{sway_user}}/.config/sway/config'

- name: Copy Sway dropin configuration
  become_user: '{{sway_user}}'
  become: yes
  copy:
    src: 'sway.config.d/'
    dest: '/home/{{sway_user}}/.config/sway/config.d'

- name: Copy Waybar configuration
  become_user: '{{sway_user}}'
  become: yes
  copy:
    src: 'waybar.config'
    dest: '/home/{{sway_user}}/.config/waybar/config'

- name: Copy Waybar styling
  become_user: '{{sway_user}}'
  become: yes
  copy:
    src: 'waybar.style.css'
    dest: '/home/{{sway_user}}/.config/waybar/style.css'

- name: Copy Alacritty configuration
  become_user: '{{sway_user}}'
  become: yes
  copy:
    src: 'alacritty.yml'
    dest: '/home/{{sway_user}}/.config/alacritty/alacritty.yml'

- name: Copy *.desktop entries
  become_user: '{{sway_user}}'
  become: yes
  copy:
    src: '{{item}}'
    dest: '/home/{{sway_user}}/.local/share/applications'
  loop:
    - 'hibernate.desktop'
    - 'logout.desktop'
    - 'reboot.desktop'
    - 'shutdown.desktop'

- name: Copy /etc/skel/.bash_profile if it does not exit
  become_user: '{{sway_user}}'
  become: yes
  copy:
    remote_src: yes
    force: no
    src: /etc/skel/.bash_profile
    dest: /home/{{sway_user}}/.bash_profile

- name: Add Sway startup command to ~/.bash_profile
  become_user: '{{sway_user}}'
  become: yes
  blockinfile:
    path: /home/{{sway_user}}/.bash_profile
    block: |
      if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
        exec sway
      fi
