# Private Ansible playbook
#
# Copyright (C) 2019 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

openssh_packages: [openssh]

sudo_group_file: 01_allow_wheel
sudo_group: wheel

cryptsetup_packages: [cryptsetup]
