# Private Ansible playbook
#
# Copyright (C) 2019 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Include tasks for installing syncthing
  include_tasks: 'install_{{ansible_facts.os_family|lower}}.yml'

- name: Include tasks for setting up a syncthing server
  include_tasks: 'server.yml'
  when: syncthing_setup_server

- name: Include tasks for starting syncthing in a user environment
  include_tasks: 'user.yml'
  when: syncthing_users is defined
