# Private Ansible playbook
#
# Copyright (C) 2019 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Ensure group '{{syncthing_server_group}}' exists
  group:
    name: '{{syncthing_server_group}}'
    state: present

- name: Ensure user '{{syncthing_server_user}}' exists
  user:
    name: '{{syncthing_server_user}}'
    home: '{{syncthing_folder_root_dir}}'
    group: '{{syncthing_server_group}}'
    state: present

- name: Create the root folder
  file:
    path: '{{item}}'
    state: directory
    owner: '{{syncthing_server_user}}'
    group: '{{syncthing_server_group}}'
    mode: 'u=rwx,g=rx,o='
  with_items:
    - '{{syncthing_folder_root_dir}}'
  when: syncthing_folder_root_dir is defined

- name: Create configuration folder structure
  file:
    path: '{{item}}'
    state: directory
    owner: '{{syncthing_server_user}}'
    group: '{{syncthing_server_group}}'
    mode: 'u=rwx,g=,o='
  with_items:
    - '{{syncthing_folder_root_dir}}/.config'
    - '{{syncthing_folder_root_dir}}/.config/syncthing'
  when: syncthing_folder_root_dir is defined

- name: Copy configuration files
  copy:
    src: '{{syncthing_files_dir}}/{{item.src}}'
    dest: '{{syncthing_folder_root_dir}}/.config/syncthing/{{item.dest}}'
    owner: '{{syncthing_server_user}}'
    group: '{{syncthing_server_group}}'
    mode: '{{item.mode}}'
  with_items: '{{syncthing_config_files}}'
  when: syncthing_files_dir is defined

- name: Enable Syncthing service for the user
  service:
    name: 'syncthing@{{syncthing_server_user}}'
    enabled: yes
    state: started
