# Private Ansible playbook
#
# Copyright (C) 2019 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Ensure group '{{syncthing_server_group}}' exists
  group:
    name: '{{syncthing_server_group}}'
    state: present

- name: Ensure user '{{syncthing_server_user}}' exists
  user:
    name: '{{syncthing_server_user}}'
    group: '{{syncthing_server_group}}'
    state: present

- name: Create the root folder containing all synchronized folders
  file:
    path: '{{syncthing_folder_root_dir}}'
    state: directory
    owner: '{{syncthing_server_user}}'
    group: '{{syncthing_server_group}}'
    mode: 'u=rwx,g=rx,o='
  when: syncthing_folder_root_dir is defined

- name: Enable Syncthing service for the user
  service:
    name: 'syncthing@{{syncthing_server_user}}'
    enabled: yes
    state: started
