# Private Ansible playbook
#
# Copyright (C) 2018 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Set time zone
  timezone:
    name: '{{timezone}}'

- name: Set the hardware clock to system time
  command: hwclock --systohc

- name: Create a backup of locale.gen
  copy:
    remote_src: yes
    force: no
    src: /etc/locale.gen
    dest: /etc/locale.gen.orig

- name: Activate locales
  locale_gen:
    name: '{{item}}'
    state: present
  with_items: '{{locales}}'

- name: Configure locale
  copy:
    dest: /etc/locale.conf
    content: "LANG={{locale}}\n"

- name: Set the keyboard layout
  copy:
    dest: /etc/vconsole.conf
    content: "KEYMAP={{keymap}}\n"

- name: Set the hostname
  hostname:
    name: '{{install_hostname}}'

- name: Add required lines to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '{{item}}'
  with_items:
    - '127.0.0.1          localhost'
    - '::1                localhost'
    - '127.0.1.1          {{install_hostname}}.localdomain         {{install_hostname}}'

