# Private Ansible playbook
#
# Copyright (C) 2018 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

##############################################################################
# Install and configure NetworkManager
##############################################################################

# See: https://wiki.archlinux.org/index.php/NetworkManager

- name: Install NetworkManager package
  package:
    name: networkmanager
    state: present

- name: Enable NetworkManager service
  service:
    name: NetworkManager
    enabled: yes

- name: Install openresolv package
  package:
    name: openresolv
    state: present
  when: nm_use_openresolv

- name: Configure NetworkManager to use openresolv
  copy:
    src: rc-manager.conf
    dest: /etc/NetworkManager/conf.d
  when: nm_use_openresolv

- name: Install the OpenVPN integraton
  package:
    name: networkmanager-openvpn
    state: present
  when: nm_install_openvpn
