# Private Ansible playbook
#
# Copyright (C) 2019 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

- name: Set time zone
  timezone:
    name: '{{timezone}}'

- name: Check if hwclock exists and can be used
  command: hwclock --test
  ignore_errors: yes
  register: hwclock_test

- name: Set the hardware clock to system time
  command: hwclock --systohc
  when: hwclock_test.rc == 0

- name: Create a backup of locale.gen
  copy:
    remote_src: yes
    force: no
    src: /etc/locale.gen
    dest: /etc/locale.gen.orig

- name: Activate locales
  locale_gen:
    name: '{{item}}'
    state: present
  with_items: '{{locales}}'

- name: Configure locale
  copy:
    dest: /etc/locale.conf
    content: "LANG={{locale}}\n"

- name: Set the keyboard layout
  copy:
    dest: /etc/vconsole.conf
    content: "KEYMAP={{keymap}}\n"

- name: Set the hostname
  hostname:
    name: '{{install_hostname}}'

- name: Create a backup of hosts file
  copy:
    remote_src: yes
    force: no
    src: /etc/hosts
    dest: /etc/hosts.orig

- name: Add required lines to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regex: '^{{item.ip|trim}}.*$'
    line: '{{item.ip}}       {{item.names}}'
  with_items:
    - {ip: '127.0.0.1', names: 'localhost'}
    - {ip: '::1      ', names: 'localhost ip6-localhost ip6-loopback'}
    - {ip: '127.0.1.1', names: '{{install_hostname}}.localdomain {{install_hostname}}'}
