# Private Ansible playbook
#
# Copyright (C) 2021 T. Himmelstoss
#
# This software may be freely distributed under the MIT license. You should
# have received a copy of the MIT License along with this program.

# See: https://wiki.archlinux.org/title/Systemd-resolved

- name: Enable and start systemd-resolved service
  service:
    name: systemd-resolved
    enabled: yes
    state: started

- name: Configure stub mode by setting the /etc/resolv.conf symlink
  file:
    path: /etc/resolv.conf
    state: link
    src: /run/systemd/resolve/stub-resolv.conf
    force: yes
    owner: root
    group: root

- name: Make sure the drop-in configuration directory exists
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Copy the drop-in configuration file for the global DNS setup
  copy:
    src: 01_global_dns.conf
    dest: /etc/systemd/resolved.conf.d/
    owner: root
    group: root
    mode: u=rw,g=r,o=r
